ifndef QUANTUM_DIR
	include ../../../../Makefile
endif

# features I don't use
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE = no
API_SYSEX_ENABLE = no
SLEEP_LED_ENABLE = no

AUDIO_ENABLE = yes
NKRO_ENABLE = yes
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = yes
